require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PetImagesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # PetImage. As you add validations to PetImage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PetImagesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all pet_images as @pet_images" do
      pet_image = PetImage.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:pet_images)).to eq([pet_image])
    end
  end

  describe "GET #show" do
    it "assigns the requested pet_image as @pet_image" do
      pet_image = PetImage.create! valid_attributes
      get :show, {:id => pet_image.to_param}, valid_session
      expect(assigns(:pet_image)).to eq(pet_image)
    end
  end

  describe "GET #new" do
    it "assigns a new pet_image as @pet_image" do
      get :new, {}, valid_session
      expect(assigns(:pet_image)).to be_a_new(PetImage)
    end
  end

  describe "GET #edit" do
    it "assigns the requested pet_image as @pet_image" do
      pet_image = PetImage.create! valid_attributes
      get :edit, {:id => pet_image.to_param}, valid_session
      expect(assigns(:pet_image)).to eq(pet_image)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new PetImage" do
        expect {
          post :create, {:pet_image => valid_attributes}, valid_session
        }.to change(PetImage, :count).by(1)
      end

      it "assigns a newly created pet_image as @pet_image" do
        post :create, {:pet_image => valid_attributes}, valid_session
        expect(assigns(:pet_image)).to be_a(PetImage)
        expect(assigns(:pet_image)).to be_persisted
      end

      it "redirects to the created pet_image" do
        post :create, {:pet_image => valid_attributes}, valid_session
        expect(response).to redirect_to(PetImage.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved pet_image as @pet_image" do
        post :create, {:pet_image => invalid_attributes}, valid_session
        expect(assigns(:pet_image)).to be_a_new(PetImage)
      end

      it "re-renders the 'new' template" do
        post :create, {:pet_image => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested pet_image" do
        pet_image = PetImage.create! valid_attributes
        put :update, {:id => pet_image.to_param, :pet_image => new_attributes}, valid_session
        pet_image.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested pet_image as @pet_image" do
        pet_image = PetImage.create! valid_attributes
        put :update, {:id => pet_image.to_param, :pet_image => valid_attributes}, valid_session
        expect(assigns(:pet_image)).to eq(pet_image)
      end

      it "redirects to the pet_image" do
        pet_image = PetImage.create! valid_attributes
        put :update, {:id => pet_image.to_param, :pet_image => valid_attributes}, valid_session
        expect(response).to redirect_to(pet_image)
      end
    end

    context "with invalid params" do
      it "assigns the pet_image as @pet_image" do
        pet_image = PetImage.create! valid_attributes
        put :update, {:id => pet_image.to_param, :pet_image => invalid_attributes}, valid_session
        expect(assigns(:pet_image)).to eq(pet_image)
      end

      it "re-renders the 'edit' template" do
        pet_image = PetImage.create! valid_attributes
        put :update, {:id => pet_image.to_param, :pet_image => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested pet_image" do
      pet_image = PetImage.create! valid_attributes
      expect {
        delete :destroy, {:id => pet_image.to_param}, valid_session
      }.to change(PetImage, :count).by(-1)
    end

    it "redirects to the pet_images list" do
      pet_image = PetImage.create! valid_attributes
      delete :destroy, {:id => pet_image.to_param}, valid_session
      expect(response).to redirect_to(pet_images_url)
    end
  end

end
